### ISSUE TITLE
[Moto G5 Plus] Stuck at loading screen

### ISSUE THREAD

**Issue by raveesh-me** [iampawan/Flutter-Music-Player#1]
The screenshot is like this:
https://photos.app.goo.gl/0M1p2weRNWJQ41V72

Please add instructions on how to take logs and file bugs. The play store app is still stuck at a loading screen.

**Comment by iampawan** [comment]
Will fix that issue in next update ..

**Comment by raveesh-me** [comment]
Restarting does not fix.
