### ISSUE TITLE
Issue in import project in android studio

### ISSUE THREAD

**Issue by jayesh28589** [iampawan/Flutter-Music-Player#10]
Hello Pawan Kumar,

Thanks for the source code uploaded to github,

I am new to Flutter (Beginner) but expert in Android.

I have download the code and import it in android studio, but it is not successfully imported.

can you please post the steps to import the source code successfully ?

Thanks

**Comment by iampawan** [comment]
There shouldn't be any problem with that.

**Comment by TooniMike** [comment]
You should just try and clone the repository
