### ISSUE TITLE
App gets stuck while scrolling

### ISSUE THREAD

**Issue by vgates** [iampawan/Flutter-Music-Player#9]
I am getting the following error when I try to scroll through the list of songs. 

`Launching lib\main.dart on Lenovo A6020a46 in debug mode...
Skipping compilation. Fingerprint match.
Built build\app\outputs\apk\debug\app-debug.apk (33.1MB).
I/FlutterActivityDelegate( 3503): onResume setting current activity to this
W/CursorWrapperInner( 3503): Cursor finalized without prior close()
I/flutter ( 3503): List<dynamic>
I/flutter ( 3503): [Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', Instance of 'Song', In
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 71 Protocol error
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 71 Protocol error
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 71 Protocol error
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-EGLSUB( 3503): <updater_thread:428>: waitFunc failed
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-ES20( 3503): <finish_current_fbo_rendering:386>: GL_OUT_OF_MEMORY
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-GSL( 3503): <gsl_ldd_control:427>: ioctl fd 39 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
W/Adreno-GSL( 3503): <log_gpu_snapshot:337>: panel.gpuSnapshotPath is not set.not generating user snapshot
W/Adreno-EGL( 3503): <qeglDrvAPI_eglSwapBuffers:3714>: EGL_CONTEXT_LOST
W/Adreno-EGL( 3503): <qeglDrvAPI_eglSwapBuffers:3714>: EGL_CONTEXT_LOST
W/Adreno-EGL( 3503): <qeglDrvAPI_eglSwapBuffers:3714>: EGL_CONTEXT_LOST
W/Adreno-EGL( 3503): <qeglDrvAPI_eglSwapBuffers:3714>: EGL_CONTEXT_LOST
W/Adreno-EGL( 3503): <qeglDrvAPI_eglSwapBuffers:3714>: EGL_CONTEXT_LOST
W/Adreno-EGL( 3503): <qeglDrvAPI_eglSwapBuffers:3714>: EGL_CONTEXT_LOST
W/Adreno-EGL( 3503): <qeglDrvAPI_eglSwapBuffers:3714>: EGL_CONTEXT_LOST
W/Adreno-EGL( 3503): <qeglDrvAPI_eglSwapBuffers:3714>: EGL_CONTEXT_LOST
`

**Comment by iampawan** [comment]
Can you try it with the release version of the apk?

**Comment by andersonmendesdev** [comment]
I am getting this error on a Fab button that displayed several speed rails and an overlay with backdrop filter, this error occurs on an asus smartphone
